[build]
  command = "CI= npm run build"

[[redirects]]
  from = "http://localhost:8000/api/*"
  to = "https://waynecartserver.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200